services:
  redis:
    image: redis:7-alpine
    container_name: is_admin_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: is_admin_backend
    # 开发模式覆盖默认 CMD，开启 Debug 和热重载
    command: flask run --host=0.0.0.0 --debug
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - env_config
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery_worker:
    build: ./backend
    container_name: is_admin_worker
    # 启动 Celery Worker
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - env_config
    environment:
      - FLASK_APP=run.py
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - backend
